// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhanKffUbflwt4VsM0enEWaxHjumczNEI',
    appId: '1:706884296191:web:65293ddb75564e24f49bca',
    messagingSenderId: '706884296191',
    projectId: 'paratotype',
    authDomain: 'paratotype.firebaseapp.com',
    storageBucket: 'paratotype.firebasestorage.app',
    measurementId: 'G-S39GCZ88ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMMi5vn1TzVI8cOmSE8QM418opTMxOVSk',
    appId: '1:706884296191:android:3dbd7a82a2d240f0f49bca',
    messagingSenderId: '706884296191',
    projectId: 'paratotype',
    storageBucket: 'paratotype.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9YdlX3apIjEOc0iwAcAHrk5uHyGiDDIQ',
    appId: '1:706884296191:ios:42eae88d6883633df49bca',
    messagingSenderId: '706884296191',
    projectId: 'paratotype',
    storageBucket: 'paratotype.firebasestorage.app',
    androidClientId: '706884296191-lrr8lqni5aj316eb3kdovqr4kbfhogti.apps.googleusercontent.com',
    iosClientId: '706884296191-o7ohcsdn726mq29pq3naglrh391s5l14.apps.googleusercontent.com',
    iosBundleId: 'com.example.para2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9YdlX3apIjEOc0iwAcAHrk5uHyGiDDIQ',
    appId: '1:706884296191:ios:42eae88d6883633df49bca',
    messagingSenderId: '706884296191',
    projectId: 'paratotype',
    storageBucket: 'paratotype.firebasestorage.app',
    androidClientId: '706884296191-lrr8lqni5aj316eb3kdovqr4kbfhogti.apps.googleusercontent.com',
    iosClientId: '706884296191-o7ohcsdn726mq29pq3naglrh391s5l14.apps.googleusercontent.com',
    iosBundleId: 'com.example.para2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhanKffUbflwt4VsM0enEWaxHjumczNEI',
    appId: '1:706884296191:web:4208f814a1427170f49bca',
    messagingSenderId: '706884296191',
    projectId: 'paratotype',
    authDomain: 'paratotype.firebaseapp.com',
    storageBucket: 'paratotype.firebasestorage.app',
    measurementId: 'G-KQPQ2EBTH1',
  );

}